language: node_js
os: linux
sudo: required
dist: trusty
node_js:
- node
before_install:
  - .travis/install-docker.sh
stages:
  - Node.js Tests
  - name: Browser Tests
    if: type = push
jobs:
  include:

  - stage: Node.js Tests
    env: NAME="Code Linting"
    script:
    - npm run format:check
  - env: NAME="Build"
    script:
    - npm run build
  - env: NAME="Unit Tests"
    script:
    - npm test
  - env: NAME="API Tests"
    script:
    - docker build test/api/ &&
      docker-compose -f test/api/docker-compose.yml up -d --build &&
      $(npm bin)/wait-on http-get://user:pass@localhost:5171/v2.3.0/info &&
      npm run test:api
  - env: NAME="Linux Browser Tests (Chrome, Firefox, Electron)"
    addons:
      chrome: stable
      firefox: latest
    before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
    script:
      - npm run test:browser
  - env: NAME="Coverage Report"
    script:
      - npm run build:test
      - "$(npm bin)/nyc --reporter=text-lcov $(npm bin)/mocha --opts mocha.opts test/index.js"
      - "$(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls"

cache:
  directories:
  - node_modules
